# used in GH Actions `.github/workflows/helm-tests.yml.jobs.unit-tests`
testing: true
ingress:
  enabled: true
  className: "nginx"
db:
  enabled: true
  settings:
    resources:
      requests:
        storage: "100Mi"
        cpu: "256m"
        memory: "1024Mi"
      limits:
        cpu: "512m"
        memory: "1024Mi"
raster:
  enabled: true
  autoscaling:
    enabled: true
    utilizationTarget:
      cpu: 65
  settings:
    resources:
      limits:
        cpu: "768m"
        memory: "4096Mi"
      requests:
        cpu: "256m"
        memory: "1024Mi"
stac:
  enabled: true
  autoscaling:
    enabled: true
    utilizationTarget:
      cpu: 65
  settings:
    resources:
      limits:
        cpu: "1280m"
        memory: "1536Mi"
      requests:
        cpu: "512m"
        memory: "1024Mi"
vector:
  enabled: true
  autoscaling:
    enabled: true
    utilizationTarget:
      cpu: 65
  settings:
    resources:
      limits:
        cpu: "768m"
        memory: "1536Mi"
      requests:
        cpu: "256m"
        memory: "1024Mi"
