# used in GH Actions `unit-tests.yml`
providerContext: "minikube"
ingress:
  enabled: false
  # used to set up NodePort in CI unittests on minikube
  className: "testing123"
db:
  enabled: true
raster:
  enabled: true
  image:
    name: local/titiler
    tag: latest
stac:
  enabled: true
  image:
    name: local/stac
    tag: latest
vector:
  enabled: true
  image:
    name: local/tipg
    tag: latest
