# used in GH Actions `unit-tests.yml`

ingress:
  enabled: false
db:
  enabled: true
raster:
  enabled: true
  image:
    name: local/titiler
    tag: latest
stac:
  enabled: false
vector:
  enabled: false
