comment_install: >
  `service` and `gitSha` are required and defaulted value keys.
  a manual installation looks like this:

  $ export GITSHA=$(git rev-parse HEAD | cut -c1-10)
  $ helm install \
      --namespace eoapi \
      --create-namespace \
      --set gitSha=$GITSHA \
      eoapi \
      ./eoapi

# the chart on the gh-pages branch will provide
# the correct updated value otherwise it's defaulted
gitSha: "gitshaABC123"


######################
# TESTING
######################
# only used in CI for running parallel helm installs
testing: false


######################
# SERVICE & INGRESS
######################
service:
  port: 8080

ingress:
  # `"nginx"` will create a `kind:Service` with a `spec.port:ClusterIP`
  # and a single Load Balancer and path rewrites for /vector, /stac, /raster
  enabled: true
  className: "nginx"
  host: ""
  tls:
    enabled: false
    secretName: eoapi-tls
    certManager: false
    certManagerIssuer: letsencrypt-prod
    certManagerEmail: ""


######################
# API SERVICES
######################
raster:
  enabled: true
  autoscaling:
    # NOTE: to have autoscaling working you'll need to install the `eoapi-support` chart
    # see ../../../docs/autoscaling.md for more information
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    # `type`: "cpu" || "requestRate" || "both"
    type: "requestRate"
    behaviour:
      scaleDown:
        stabilizationWindowSeconds: 60
      scaleUp:
        stabilizationWindowSeconds: 0
    targets:
      # matches `type` value above unless `type: "both"` is selected
      cpu: 85
      requestRate: 10000
  image:
    name: ghcr.io/stac-utils/titiler-pgstac
    tag: uvicorn-1.2.0
  command:
    - "uvicorn"
    - "titiler.pgstac.main:app"
    - "--host=$(HOST)"
    - "--port=$(PORT)"
  settings:
    timeout: 10
    # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    resources:
      limits:
        cpu: "768m"
        memory: "4096Mi"
      requests:
        cpu: "256m"
        memory: "3072Mi"
    envVars:
      ##############
      # titiler
      ##############
      CPL_VSIL_CURL_ALLOWED_EXTENSIONS: ".tif,.TIF,.tiff"
      GDAL_CACHEMAX: "200"  # 200 mb
      GDAL_DISABLE_READDIR_ON_OPEN: "EMPTY_DIR"
      GDAL_INGESTED_BYTES_AT_OPEN: "32768"
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: "YES"
      GDAL_HTTP_MULTIPLEX: "YES"
      GDAL_HTTP_VERSION: "2"
      PYTHONWARNINGS: "ignore"
      VSI_CACHE: "TRUE"
      VSI_CACHE_SIZE: "5000000"  # 5 MB (per file-handle)
      ##############
      # uvicorn
      ##############
      HOST: "0.0.0.0"
      PORT: "8080"
      # https://www.uvicorn.org/settings/#production
      WEB_CONCURRENCY: "10"

stac:
  enabled: true
  autoscaling:
    # NOTE: to have autoscaling working you'll need to install the `eoapi-support` chart
    # see ../../../docs/autoscaling.md for more information
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    # `type`: "cpu" || "requestRate" || "both"
    type: "requestRate"
    behaviour:
      scaleDown:
        stabilizationWindowSeconds: 60
      scaleUp:
        stabilizationWindowSeconds: 0
    targets:
      # matches `type` value above unless `type: "both"` is selected
      cpu: 85
      requestRate: 15000
  image:
    name: ghcr.io/stac-utils/stac-fastapi-pgstac
    tag: 2.4.9
  command:
    - "uvicorn"
    - "stac_fastapi.pgstac.app:app"
    - "--host=$(HOST)"
    - "--port=$(PORT)"
  settings:
    timeout: 10
    # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    resources:
      limits:
        cpu: "768m"
        memory: "1024Mi"
      requests:
        cpu: "256m"
        memory: "1024Mi"
    envVars:
      ##############
      # uvicorn
      ##############
      HOST: "0.0.0.0"
      PORT: "8080"
      # https://www.uvicorn.org/settings/#production
      WEB_CONCURRENCY: "10"

vector:
  enabled: true
  autoscaling:
    # NOTE: to have autoscaling working you'll need to install the `eoapi-support` chart
    # see ../../../docs/autoscaling.md for more information
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    # `type`: "cpu" || "requestRate" || "both"
    type: "requestRate"
    behaviour:
      scaleDown:
        stabilizationWindowSeconds: 60
      scaleUp:
        stabilizationWindowSeconds: 0
    targets:
      # matches `type` value above unless `type: "both"` is selected
      cpu: 85
      requestRate: 15000
  image:
    name: ghcr.io/developmentseed/tipg
    tag: uvicorn-0.6.1
  command:
    - "uvicorn"
    - "tipg.main:app"
    - "--host=$(HOST)"
    - "--port=$(PORT)"
  settings:
    timeout: 10
    # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    resources:
      limits:
        cpu: "768m"
        memory: "1024Mi"
      requests:
        cpu: "256m"
        memory: "256Mi"
    envVars:
      ##############
      # tipg
      ##############
      TIPG_CATALOG_TTL: "0"
      ##############
      # uvicorn
      ##############
      HOST: "0.0.0.0"
      PORT: "8080"
      # https://www.uvicorn.org/settings/#production
      WEB_CONCURRENCY: "10"

docServer:
  enabled: true
