contact_links:
  - name: Ask questions
    url: https://github.com/developmentseed/eoapi/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Feature Request / Ideas
    url: https://github.com/developmentseed/eoapi/discussions/categories/general
    about: Please share your ideas or feature requests here.
