---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgstac
  labels:
    app: pgstac
spec:
  selector:
    matchLabels:
      app: pgstac
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgstac
    spec:
      restartPolicy: Always
      containers:
        - name: pgstac
          image: {{ .Values.db.image.name }}:{{ .Values.db.image.tag }}
          args:
            - "postgres"
            - "-N"
            - "500"
          envFrom:
          - secretRef:
              name: pgstac-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgstac-claim
        {{- if .Values.db.enable_data_fixtures }}
        - name: loader
          image: {{ .Values.db.image.name }}:{{ .Values.db.image.tag }}
          command:
            - "sh"
          args:
            - "/opt/initdb/load.sh"
          envFrom:
            - secretRef:
                name: pgstac-secrets
          ports:
            - containerPort: 6543
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgstac-claim
            - mountPath: /opt/initdb/sql-data
              name: initdb-sql-volume
            - mountPath: /opt/initdb/json-data
              name: initdb-json-volume
            - mountPath: /opt/initdb/
              name: initdb-sh-volume
        {{- end }}
      volumes:
        - name: pgstac-claim
          persistentVolumeClaim:
            claimName: pgstac-claim
        - name: initdb-sql-volume
          configMap:
            name: initdb-sql-config
        - name: initdb-json-volume
          configMap:
            name: initdb-json-config
        - name: initdb-sh-volume
          configMap:
            name: initdb-sh-config
