name: CI

# On every pull request, but only on push to main
on:
  push:
    branches:
    - '*'
    tags:
    - '*'
    paths:
    # only run jobs if some code have changed
    - 'helm-chart/eoapi/**'
  pull_request:

jobs:
  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: d3adb5/helm-unittest-action@v2
        with:
          helm-version: v3.8.2
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          cd helm-chart
          helm unittest eoapi -f 'tests/*.yaml' -v eoapi/required-test-values.yaml

