name: release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v3
        with:
          helm-version: v3.8.2
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install_only: true
        run: |
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          chart="helm-chart/eoapi/Chart.yaml"
          chart_changes_prev_commit=$(git diff --find-renames --name-only HEAD~ -- "$chart")
          if [[ -n "$chart_changes_prev_commit" ]]; then
            echo "[ CHANGES FOUND ]:"
            echo "###############################"
            echo $chart_changes_prev_commit
            echo "###############################"

            rm -rf .cr-release-packages
            mkdir -p .cr-release-packages

            rm -rf .cr-index
            mkdir -p .cr-index

            ############ PACKAGE
            cr package "$chart" --package-path .cr-release-packages

            ############ RELEASE
            cr upload -o "$owner" -r "$repo" -c "$(git rev-parse HEAD)"

            ############ INDEX
            cr index -o "$owner" -r "$repo" --push
          else
            echo "Nothing to do, nothing changed in the chart dir..."
          fi



