name: release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: debug
        run: |
          lookup_latest_tag() {
              git fetch --tags > /dev/null 2>&1

              if ! git describe --tags --abbrev=0 HEAD~ 2> /dev/null; then
                  git rev-list --max-parents=0 --first-parent HEAD
              fi
          }
          local commit=$(lookup_latest_tag)
          local changed_files
          local charts_dir="helm-chart"

          git diff --find-renames --name-only "$commit" -- "$charts_dir"
          changed_files=$(git diff --find-renames --name-only "$commit" -- "$charts_dir")

          "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l

          tr "/" "\n" <<< "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l

          local depth=$(( $(tr "/" "\n" <<< "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l) + 1 ))
          local fields="1-${depth}"
          cut -d '/' -f "$fields" <<< "$changed_files" | uniq | filter_charts

      - uses: azure/setup-helm@v3
        with:
          helm-version: v3.8.2
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: helm-chart
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
