name: release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: debug
        run: |
          lookup_latest_tag() {
              git fetch --tags > /dev/null 2>&1

              if ! git describe --tags --abbrev=0 HEAD~ 2> /dev/null; then
                  git rev-list --max-parents=0 --first-parent HEAD
              fi
          }
          commit=$(lookup_latest_tag)
          charts_dir="helm-chart"

          first=$(git diff --find-renames --name-only "$commit")
          echo "CHANGED_FIRST=$first"
          second=$(git diff --find-renames --name-only "$commit" -- "$charts_dir")
          echo "SECOND=$second"
          changed_files=$(git diff --find-renames --name-only "$commit" -- "$charts_dir")
          echo "CHANGED_FILES=$changed_files"

          "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l

          tr "/" "\n" <<< "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l

          depth=$(( $(tr "/" "\n" <<< "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l) + 1 ))
          echo "DEPTH=$depth"
          fields="1-${depth}"
          echo "FIELDS=$fields"

          filter_charts() {
              while read -r chart; do
                  echo "CHART=$chart"
                  [[ ! -d "$chart" ]] && continue
                  local file="$chart/Chart.yaml"
                  if [[ -f "$file" ]]; then
                      echo "$chart"
                  else
                     echo "WARNING: $file is missing, assuming that '$chart' is not a Helm chart. Skipping." 1>&2
                  fi
              done
          }

          cut -d '/' -f "$fields" <<< "$changed_files" | uniq | filter_charts

      - uses: azure/setup-helm@v3
        with:
          helm-version: v3.8.2
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -z "$(git diff --find-renames --name-only $(git rev-parse HEAD) -- helm-chart)" ]]; then
            
          fi


