name: release

on:
  workflow_dispatch:
    branches:
      - gh-pages

jobs:
  release:
    if: github.actor == 'ranchodeluxe' || github.actor == 'gcorradini'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          helm-version: v3.8.2

      - name: helm release packages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # package recent chart
          chart="helm-chart/eoapi"
          helm package $chart --destination .

          # create the index file
          helm repo index .

          git add -A
          chart_version=$(cat $chart/Chart.yaml| grep version: | cut -d' ' -f2)
          git commit -m $chart_version

      - name: commit release and push
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: gh-pages
